ankiconnect: false
attention_c: Fore.LIGHTYELLOW_EX
break: false
bulk_add: false
bulk_free_def: false
bulk_free_syn: false
center: 79* auto
deck: '-'
def1_c: Fore.RESET
def2_c: Fore.RESET
def_blk: 0
delimit_c: Fore.RESET
delimsize: 79* auto
disambiguation: true
dodaj_audio: true
dodaj_czesci_mowy: true
dodaj_definicje: true
dodaj_etymologie: true
dodaj_przyklady_idiomow: true
dodaj_przyklady_synonimow: true
dodaj_synonimy: true
dodaj_wlasne_zdanie: true
duplicates: false
dupscope: deck
error_c: Fore.LIGHTRED_EX
etym_blk: 0
etym_c: Fore.RESET
fieldorder:
  '1': definicje
  '2': disambiguation
  '3': correct_word
  '4': zdanie
  '5': czesci_mowy
  '6': etymologia
  '7': audiofile
indent: 2
index_c: Fore.LIGHTGREEN_EX
input_c: Fore.RESET
inputtext_c: Fore.RESET
note: '-'
pidiom_blk: 0
pidiom_c: Fore.RESET
pokazuj_filtrowany_slownik: true
pos_blk: 0
pos_c: Fore.YELLOW
psyn_blk: 0
psyn_c: Fore.RESET
save_path: Karty_audio
showcard: true
showdisamb: true
syn_blk: 0
syn_c: Fore.YELLOW
syndef_c: Fore.RESET
synpos_c: Fore.RESET
tags: dodawacz
textwidth: 79
tworz_karte: true
ukryj_przyimki: false
ukryj_slowo_w_definicji: true
ukryj_slowo_w_disamb: true
ukryj_slowo_w_idiom: true
ukryj_slowo_w_zdaniu: false
word_c: Fore.CYAN
wrap_text: true
