bulk_add: false
def1_color: Fore.RESET
def2_color: Fore.RESET
delimit_color: Fore.RESET
disambiguation: true
dodaj_audio: true
dodaj_czesci_mowy: true
dodaj_definicje: true
dodaj_etymologie: true
dodaj_przyklady_synonimow: true
dodaj_synonimy: true
dodaj_wlasne_zdanie: true
error_color: Fore.LIGHTRED_EX
etym_color: Fore.RESET
gloss_color: Fore.CYAN
index_color: Fore.LIGHTGREEN_EX
input_color: Fore.RESET
inputtext_color: Fore.RESET
pokazuj_filtrowany_slownik: true
pos_color: Fore.YELLOW
psyn_color: Fore.RESET
save_path: Karty_audio
syn_color: Fore.YELLOW
syndef_color: Fore.RESET
synpos_color: Fore.RESET
tworz_karte: true
ukryj_slowo_w_definicji: true
ukryj_slowo_w_disamb: true
ukryj_slowo_w_zdaniu: false
