ankiconnect: false
attention_c: lightyellow
break: false
bulk_add: false
bulk_free_def: false
bulk_free_syn: false
center: 79* auto
deck: '-'
def1_c: reset
def2_c: reset
def_blk: 0
delimit_c: reset
delimsize: 79* auto
disambiguation: true
dodaj_audio: true
dodaj_czesci_mowy: true
dodaj_definicje: true
dodaj_etymologie: true
dodaj_przyklady_idiomow: true
dodaj_przyklady_synonimow: true
dodaj_synonimy: true
dodaj_wlasne_zdanie: true
duplicates: false
dupscope: deck
error_c: lightred
etym_blk: 0
etym_c: reset
fieldorder:
  '1': definicja
  '2': synonimy
  '3': przyklady
  '4': phrase
  '5': zdanie
  '6': czesci_mowy
  '7': etymologia
  '8': audio
fieldorder_d: '3'
indent: 2
index_c: lightgreen
input_c: reset
inputtext_c: reset
mergedisamb: false
mergeidiom: true
note: '-'
pidiom_blk: 0
pidiom_c: reset
pokazuj_filtrowany_slownik: true
pos_blk: 0
pos_c: yellow
psyn_blk: 0
psyn_c: reset
save_path: Karty_audio
server: ahd
showcard: true
showdisamb: true
syn_blk: 0
syn_c: yellow
syndef_c: reset
synpos_c: reset
tags: dodawacz
textwidth: 79
tworz_karte: true
ukryj_przyimki: false
ukryj_slowo_w_definicji: true
ukryj_slowo_w_disamb: true
ukryj_slowo_w_idiom: true
ukryj_slowo_w_zdaniu: false
word_c: cyan
wrap_text: true
