break: false
bulk_add: false
bulk_free_def: false
bulk_free_syn: false
center: 79
def1_color: Fore.RESET
def2_color: Fore.RESET
def_bulk: 0
delimit_color: Fore.RESET
delimsize: 79
disambiguation: true
dodaj_audio: true
dodaj_czesci_mowy: true
dodaj_definicje: true
dodaj_etymologie: true
dodaj_przyklady_synonimow: true
dodaj_synonimy: true
dodaj_wlasne_zdanie: true
error_color: Fore.LIGHTRED_EX
etym_bulk: 0
etym_color: Fore.RESET
gloss_color: Fore.CYAN
indent: 2
index_color: Fore.LIGHTGREEN_EX
input_color: Fore.RESET
inputtext_color: Fore.RESET
pokazuj_filtrowany_slownik: true
pos_bulk: 0
pos_color: Fore.YELLOW
psyn_bulk: 0
psyn_color: Fore.RESET
save_path: Karty_audio
syn_bulk: 0
syn_color: Fore.YELLOW
syndef_color: Fore.RESET
synpos_color: Fore.RESET
textwidth: 79
tworz_karte: true
ukryj_slowo_w_definicji: true
ukryj_slowo_w_disamb: true
ukryj_slowo_w_zdaniu: false
wrap_text: true
