add_audio: true
add_definitions: true
add_etymologies: true
add_example_sentences: true
add_parts_of_speech: true
add_sentences: true
add_synonyms: true
ankiconnect: false
attention_c: lightyellow
audio: auto
audio_device: default
audio_path: Karty_audio
convert_to_ipa: true
create_card: true
deck: '-'
def1_c: reset
def2_c: reset
def_bulk: auto
defsign_c: cyan
delimit_c: reset
dict: ahd
dict2: idioms
displaycard: true
dupescope: deck
duplicates: false
error_c: lightred
etym_bulk: auto
etym_c: reset
exsen_bulk: auto
exsen_c: lightblack
fieldorder:
  '1': definicja
  '2': synonimy
  '3': przyklady
  '4': phrase
  '5': zdanie
  '6': czesci_mowy
  '7': etymologia
  '8': audio
  '9': sentence_audio
fieldorder_d: '3'
hide_definition_word: true
hide_example_sentence_word: true
hide_prepositions: false
hide_sentence_example_word: true
hide_sentence_word: false
hide_synonym_word: true
hideas: '...'
indent:
- 2
- ''
index_c: lightgreen
inflection_c: lightblack
input_c: reset
inputtext_c: reset
keep_endings: true
nolabel_filter: false
note: '-'
phon_c: lightblack
phrase_c: cyan
pos_bulk: auto
pos_c: yellow
poslabel_c: lightwhite
recording_quality: '4'
save_card: true
showadded: true
showexsen: true
subdef_filter: false
success_c: lightgreen
syn_bulk: auto
syn_c: yellow
syngloss_c: reset
tags: dodawacz
textwidth:
- 79
- ''
textwrap: regular
thesaurus: wordnet
top: true
