add_audio: true
add_definitions: true
add_disambiguation: true
add_etymologies: true
add_idiom_examples: true
add_parts_of_speech: true
add_sentences: true
add_synonym_examples: false
add_synonyms: false
ahd_filter: false
ankiconnect: false
attention_c: lightyellow
audio_device: default
audio_path: Karty_audio
center: 79* auto
convert_to_ipa: true
create_card: true
deck: '-'
def1_c: reset
def2_c: reset
def_bulk: '0'
defsign_c: cyan
delimit_c: reset
delimsize: 79* auto
displaycard: true
dupescope: deck
duplicates: false
error_c: lightred
etym_bulk: '0'
etym_c: reset
fieldorder:
  '1': definicja
  '2': synonimy
  '3': przyklady
  '4': phrase
  '5': zdanie
  '6': czesci_mowy
  '7': etymologia
  '8': audio
  '9': sentence_audio
fieldorder_d: '3'
hide_definition_word: true
hide_idiom_example_word: true
hide_idiom_word: true
hide_prepositions: false
hide_sentence_word: false
hide_synonym_example_word: true
hide_synonym_word: true
hideas: '...'
indent: 2
index_c: lightgreen
inflection_c: lightblack
input_c: reset
inputtext_c: reset
keep_endings: true
merge_disambiguation: false
merge_idioms: true
nolabel_filter: false
note: '-'
phon_c: lightblack
phrase_c: cyan
pidiom_bulk: '0'
pidiom_c: reset
pos_bulk: '0'
pos_c: yellow
poslabel_c: lightwhite
psyn_bulk: '0'
psyn_c: reset
psyn_filter: true
recording_quality: '4'
save_card: true
server: ahd
showadded: true
success_c: lightgreen
syn_bulk: '0'
syn_c: yellow
syngloss_c: reset
synpos_c: lightblack
tags: dodawacz
text_justification: false
textwidth: 79
wraptext: true
